### ISSUE TITLE
Are there any prebuilt binaries available?

### ISSUE THREAD

**Issue by ghost** [brennschlus/minimal_notes#1]
I wanna try this out, but my underpowered PC doesn't let me run Android Studio properly. Could you build an Android package of this app?

**Comment by brennschlus** [comment]
@kskeigrshi I will add them latter in Releases page.

**Comment by ghost** [comment]
Спасибо

**Comment by brennschlus** [comment]
@kskeigrshi I build first release https://github.com/brennschlus/minimal_notes/releases/tag/v1.0.0
