### ISSUE TITLE
Null name when deleting note

### ISSUE THREAD

**Issue by ghost** [brennschlus/minimal_notes#2]
![Screenshot_20211224-100715](https://user-images.githubusercontent.com/90227297/147304662-edc4f1d0-ffd3-4685-8a30-3b00a94b6202.jpg)
I think it's a wrong variable name.

**Comment by brennschlus** [comment]
@kskeigrshi yeah, it parse note text instead of title, I will add condition if title is null then it will be text

**Comment by ghost** [comment]
I think "note '${TITLE} - ${CONTENTS} has been succesfully deleted" will be better

**Comment by brennschlus** [comment]
@kskeigrshi good suggestion! I uploaded new version to release https://github.com/brennschlus/minimal_notes/releases/tag/v1.0.1
